alter session set query_tag = 'SSIS_BATCH_LOAD';

use database SSIS_DB;
use schema MUSIC;
use warehouse COMPUTE_WH;

CREATE FILE FORMAT IF NOT EXISTS FILE_FORMAT_CSV_GZIPPED TYPE = 'CSV' COMPRESSION = 'GZIP' empty_field_as_null=true FIELD_DELIMITER = '|' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\042' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' ;

create TABLE IF NOT EXISTS SPOTIFY_RANKING (
	POSITION NUMBER(38,0),
	TRACK_NAME VARCHAR(150),
	ARTIST VARCHAR(60),
	STREAMS NUMBER(38,0),
	URL VARCHAR(100),
	DATE DATE,
	REGION VARCHAR(50),
	PK NUMBER(38,0)
);

create TABLE IF NOT EXISTS TOP_TRACKS_OF_2018 (
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	ARTISTS VARCHAR(50) NOT NULL,
	DANCEABILITY FLOAT NOT NULL,
	ENERGY FLOAT NOT NULL,
	KEY FLOAT NOT NULL,
	LOUDNESS FLOAT NOT NULL,
	MODE FLOAT NOT NULL,
	SPEECHINESS FLOAT NOT NULL,
	ACOUSTICNESS FLOAT NOT NULL,
	INSTRUMENTALNESS FLOAT NOT NULL,
	LIVENESS FLOAT NOT NULL,
	VALENCE FLOAT NOT NULL,
	TEMPO FLOAT NOT NULL,
	DURATION_MS FLOAT NOT NULL,
	TIME_SIGNATURE FLOAT NOT NULL,
	PK NUMBER(38,0)
);

begin transaction;

PUT file://C:\Users\PLakhanpal\Documents\Snowflake\Articles\SQLServerExportedFiles\spotify_ranking\*.gz '@~/SPOTIFY_RANKING/DATA' AUTO_COMPRESS=false PARALLEL=99 SOURCE_COMPRESSION=GZIP overwrite=true;

CREATE TEMPORARY TABLE "SPOTIFY_RANKING_TEMP" LIKE "SPOTIFY_RANKING";

COPY INTO SPOTIFY_RANKING_TEMP("POSITION", "TRACK_NAME", "ARTIST", "STREAMS", "URL", "DATE", "REGION", "PK") 
FROM 
(select $1 AS "POSITION", $2 as "TRACK_NAME", $3 AS "ARTIST", $4 AS "STREAMS", $5 AS "URL", to_date($6, 'mm/dd/yyyy hh:mi:ss pm') as "DATE", $7 AS "REGION",$8 AS "PK" from '@~/SPOTIFY_RANKING/DATA' (file_format=>FILE_FORMAT_CSV_GZIPPED)) on_error='CONTINUE'
;

MERGE INTO "SPOTIFY_RANKING" T USING "SPOTIFY_RANKING_TEMP" AS S ON T."PK" = S."PK"
WHEN MATCHED THEN UPDATE SET  T."ARTIST"=S."ARTIST", T."DATE"=S."DATE", T."PK"=S."PK", T."POSITION"=S."POSITION", T."REGION"=S."REGION", T."STREAMS"=S."STREAMS", T."TRACK_NAME"=S."TRACK_NAME", T."URL"=S."URL"
WHEN NOT MATCHED THEN INSERT("ARTIST", "DATE", "PK", "POSITION", "REGION", "STREAMS", "TRACK_NAME", "URL") VALUES(S."ARTIST" , S."DATE" , S."PK" , S."POSITION" , S."REGION" , S."STREAMS" , S."TRACK_NAME" , S."URL");

RM '@~/SPOTIFY_RANKING/DATA';

commit;

begin transaction;

PUT file://C:\Users\PLakhanpal\Documents\Snowflake\Articles\SQLServerExportedFiles\top_tracks_of_2018\*.gz '@~/TOP_TRACKS_OF_2018/DATA' AUTO_COMPRESS=false PARALLEL=99 SOURCE_COMPRESSION=GZIP overwrite=true;

CREATE TEMPORARY TABLE "TOP_TRACKS_OF_2018_TEMP" LIKE "TOP_TRACKS_OF_2018";

COPY INTO TOP_TRACKS_OF_2018_TEMP("ID", "NAME", "ARTISTS", "DANCEABILITY", "ENERGY", "KEY", "LOUDNESS", "MODE", "SPEECHINESS", "ACOUSTICNESS", "INSTRUMENTALNESS", "LIVENESS", "VALENCE", "TEMPO", "DURATION_MS", "TIME_SIGNATURE", "PK") 
FROM 
(select $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17 from '@~/TOP_TRACKS_OF_2018/DATA' (file_format=>FILE_FORMAT_CSV_GZIPPED)) on_error='CONTINUE'
;

MERGE INTO "TOP_TRACKS_OF_2018" T USING "TOP_TRACKS_OF_2018_TEMP" AS S ON T."PK" = S."PK"
WHEN MATCHED THEN UPDATE SET  T."ID"=S."ID", T."NAME"=S."NAME", T."ARTISTS"=S."ARTISTS", T."DANCEABILITY"=S."DANCEABILITY", T."ENERGY"=S."ENERGY", T."KEY"=S."KEY", T."LOUDNESS"=S."LOUDNESS", T."MODE"=S."MODE", T."SPEECHINESS"=S."SPEECHINESS", T."ACOUSTICNESS"=S."ACOUSTICNESS", T."INSTRUMENTALNESS"=S."INSTRUMENTALNESS", T."LIVENESS"=S."LIVENESS", T."VALENCE"=S."VALENCE", T."TEMPO"=S."TEMPO", T."DURATION_MS"=S."DURATION_MS", T."TIME_SIGNATURE"=S."TIME_SIGNATURE", T."PK"=S."PK"
WHEN NOT MATCHED THEN INSERT("ID", "NAME", "ARTISTS", "DANCEABILITY", "ENERGY", "KEY", "LOUDNESS", "MODE", "SPEECHINESS", "ACOUSTICNESS", "INSTRUMENTALNESS", "LIVENESS", "VALENCE", "TEMPO", "DURATION_MS", "TIME_SIGNATURE", "PK") VALUES(S."ID" , S."NAME" , S."ARTISTS" , S."DANCEABILITY" , S."ENERGY" , S."KEY" , S."LOUDNESS" , S."MODE", S."SPEECHINESS", S."ACOUSTICNESS", S."INSTRUMENTALNESS", S."LIVENESS", S."VALENCE", S."TEMPO", S."DURATION_MS", S."TIME_SIGNATURE", "PK");

RM '@~/TOP_TRACKS_OF_2018/DATA';

commit;

alter session unset query_tag;